name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'    # Updated from 11 to 17
        distribution: 'temurin'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer
        pip install cython

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install Android tools
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          wget \
          unzip \
          python3-pip \
          build-essential \
          git \
          python3 \
          python3-dev \
          ffmpeg \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          zlib1g-dev \
          libgstreamer1.0 \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          libzbar-dev \
          build-essential \
          libgl1 \
          libgles2 \
          libgstreamer1.0-dev \
          gstreamer1.0-gtk3 \
          python3-setuptools \
          libsqlite3-dev \
          zlib1g-dev \
          libbz2-dev \
          libncurses5-dev \
          libgdbm-dev \
          libnss3-dev \
          libssl-dev \
          libreadline-dev \
          libffi-dev \
          libsqlite3-dev \
          liblzma-dev \
          autoconf \
          lld \
          libtool \
          pkg-config \
          ccache

    - name: Set up Android SDK components
      run: |
        export JAVA_HOME="/opt/java/17"
        export PATH="$JAVA_HOME/bin:$PATH"
        yes | sdkmanager --licenses || true
        sdkmanager --install "platforms;android-33" "build-tools;33.0.0" "ndk;23.1.7779620" "platform-tools"

    - name: Create buildozer.spec
      run: |
        echo "[app]" > buildozer.spec
        echo "title = Document Scanner" >> buildozer.spec
        echo "package.name = documentscanner" >> buildozer.spec
        echo "package.domain = org.scanner" >> buildozer.spec
        echo "source.dir = ." >> buildozer.spec
        echo "source.include_exts = py,png,jpg,kv,atlas,txt" >> buildozer.spec
        echo "version = 1.0" >> buildozer.spec
        echo "requirements = python3,kivy,plyer,requests" >> buildozer.spec
        echo "orientation = portrait" >> buildozer.spec
        echo "osx.python_version = 3" >> buildozer.spec
        echo "osx.kivy_version = 2.1.0" >> buildozer.spec
        echo "fullscreen = 0" >> buildozer.spec
        echo "android.permissions = READ_EXTERNAL_STORAGE,WRITE_EXTERNAL_STORAGE" >> buildozer.spec
        echo "android.api = 33" >> buildozer.spec
        echo "android.minapi = 21" >> buildozer.spec
        echo "android.sdk = 33" >> buildozer.spec
        echo "android.ndk = 23.1.7779620" >> buildozer.spec
        echo "android.accept_sdk_license = True" >> buildozer.spec
        echo "android.arch = arm64-v8a" >> buildozer.spec
        echo "p4a.branch = master" >> buildozer.spec
        echo "android.gradle_dependencies = androidx.core:core:1.6.0" >> buildozer.spec
        echo "" >> buildozer.spec
        echo "[buildozer]" >> buildozer.spec
        echo "log_level = 2" >> buildozer.spec
        echo "warn_on_root = 1" >> buildozer.spec

    - name: Build Android APK
      run: |
        export JAVA_HOME="/opt/java/17"
        export PATH="$JAVA_HOME/bin:$PATH"
        export ANDROID_HOME=/usr/local/lib/android/sdk
        export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/23.1.7779620
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk
        retention-days: 90
